### ISSUE TITLE
Storage of Secrets

### ISSUE THREAD

**Issue by kid286** [rogerta/secrets-for-android#137]
Secrets for Android is a great app.
When I migrated from a Galaxy III to a Nexus 5x and installed Secrets for Android an old set of secrets appeared on the Nexus 5x.  
Where did this old data come from?
How can I remove an external copy of my data?
I do not want to have personal information stored on the cloud or in my Google account.
Thanks
Tim

**Comment by rogerta** [comment]
Hi Tim,

Secrets uses a system built into android (
http://developer.android.com/guide/topics/data/backup.html) to backup your
secrets to your google account in the cloud.  The secrets are transmitted
and stored encrypted.  Secrets does this automatically.  This is to help
safeguard your secrets should you loose your phone and makes it easier to
transfer to a new phone.

If you really don't want an encrypted backup in the cloud, then you'll have
to stop using secrets and uninstall it.    Sorry that wasn't clear.  You
can use the export feature to takeout your data in an unencrypted form.

=================================================
Roger Tawa
http://tawacentral.net/
[When you stop, you're done.]

**Comment by bcwhite0** [comment]
Maybe there could be an option to disabled the backup within Secrets but that turns out to be very dangerous.  If you put something important there and then the phone is lost/broken/reset/whatever, it's gone without chance of recovery.  Since it was important enough to put into an encrypted file, it's very possible that there are no other copies and thus irretrievably lost.
